[package]
name = "vixeeny-encode"
description = "Vixeeny: encode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ffmpeg-next = { version = "9.0.0", default-features = false, features = ["codec", "format", "software-scaling", "static"], optional = true }

[features]
ffmpeg-next = ["dep:ffmpeg-next"]
