// SPDX-License-Identifier: GPL-3.0-or-later
//! Raw bindings to libavif and libjxl, generated by `build.rs`.
#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
    missing_docs
)]

include!(concat!(env!("OUT_DIR"), "/native.rs"));
