[package]
name = "vixeeny-app"
description = "Vixeeny: app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
vixeeny-common = { path = "../vixeeny-common" }

[lints]
workspace = true
