[package]
name = "vixeeny-app"
description = "Vixeeny: app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
vixeeny-capture = { path = "../vixeeny-capture" }
vixeeny-common = { path = "../vixeeny-common" }
vixeeny-image = { path = "../vixeeny-image" }
vixeeny-platform = { path = "../vixeeny-platform" }

[dev-dependencies]
png.workspace = true

[lints]
workspace = true
