[package]
name = "vixeeny-convert"
description = "Vixeeny: convert"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
vixeeny-image = { path = "../vixeeny-image" }

[features]
native-codecs = ["vixeeny-image/native-codecs"]

[dev-dependencies]
png.workspace = true
