#!/usr/bin/env python3
"""Regenerates ui/icons.slint from Microsoft's Fluent UI System Icons (MIT).

    python3 crates/vixeeny-ui/tools/gen_icons.py

Each icon is the `d` attribute(s) of the 20 px SVG, joined into one path string.
"""
import re, sys, urllib.parse, urllib.request, pathlib

BASE = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets"
# slint name -> (folder, style)
ICONS = {
    "camera": ("Camera", "regular"), "record": ("Record", "regular"), "record-filled": ("Record", "filled"),
    "pause": ("Pause", "regular"), "pause-filled": ("Pause", "filled"),
    "play": ("Play", "regular"), "play-filled": ("Play", "filled"),
    "stop": ("Stop", "regular"), "stop-filled": ("Stop", "filled"),
    "settings": ("Settings", "regular"), "image": ("Image", "regular"), "video": ("Video", "regular"),
    "folder": ("Folder", "regular"), "folder-open": ("Folder Open", "regular"),
    "copy": ("Copy", "regular"), "delete": ("Delete", "regular"), "open": ("Open", "regular"),
    "save": ("Save", "regular"), "save-as": ("Save Copy", "regular"),
    "dismiss": ("Dismiss", "regular"), "checkmark": ("Checkmark", "regular"),
    "chevron-down": ("Chevron Down", "regular"), "chevron-up": ("Chevron Up", "regular"),
    "chevron-right": ("Chevron Right", "regular"), "chevron-left": ("Chevron Left", "regular"),
    "info": ("Info", "regular"), "warning": ("Warning", "regular"), "error": ("Error Circle", "regular"),
    "keyboard": ("Keyboard", "regular"), "mic": ("Mic", "regular"), "mic-off": ("Mic Off", "regular"),
    "speaker": ("Speaker 2", "regular"), "headphones": ("Headphones", "regular"),
    "window": ("Window", "regular"), "window-multiple": ("Window Multiple", "regular"),
    "desktop": ("Desktop", "regular"), "dual-screen": ("Dual Screen", "regular"),
    "scan-text": ("Scan Text", "regular"), "text": ("Text T", "regular"),
    "eyedropper": ("Eyedropper", "regular"), "crop": ("Crop", "regular"),
    "undo": ("Arrow Undo", "regular"), "redo": ("Arrow Redo", "regular"),
    "pen": ("Pen", "regular"), "highlight": ("Highlight", "regular"), "square": ("Square", "regular"),
    "circle": ("Circle", "regular"), "line": ("Line", "regular"), "arrow": ("Arrow Up Right", "regular"),
    "cursor": ("Cursor", "regular"), "blur": ("Blur", "regular"), "marker": ("Number Circle 1", "regular"),
    "scroll": ("Arrow Autofit Height", "regular"), "pixelate": ("Grid", "regular"),
    "sync": ("Arrow Sync", "regular"), "add": ("Add", "regular"), "subtract": ("Subtract", "regular"),
    "search": ("Search", "regular"), "globe": ("Globe", "regular"), "history": ("History", "regular"),
    "wrench": ("Wrench", "regular"), "color": ("Color", "regular"), "sparkle": ("Sparkle", "regular"),
    "timer": ("Timer", "regular"), "eye": ("Eye", "regular"), "clipboard": ("Clipboard", "regular"),
    "rename": ("Rename", "regular"), "home": ("Home", "regular"), "plug": ("Plug Connected", "regular"),
    "more": ("More Horizontal", "regular"), "download": ("Arrow Download", "regular"),
    "images": ("Image Multiple", "regular"), "video-clip": ("Video Clip", "regular"),
    "sound-source": ("Sound Source", "regular"), "device": ("Device EQ", "regular"),
    "checkmark-circle": ("Checkmark Circle", "regular"), "moon": ("Weather Moon", "regular"),
    "sun": ("Weather Sunny", "regular"), "paint": ("Paint Brush", "regular"), "document": ("Document", "regular"),
    "convert": ("Convert Range", "regular"), "app": ("App Folder", "regular"), "apps": ("Apps List", "regular"),
    "resize": ("Resize", "regular"), "screenshot": ("Screenshot", "regular"), "star": ("Star", "regular"),
    "arrow-right": ("Arrow Right", "regular"), "alert": ("Alert", "regular"), "slider": ("Options", "regular"),
    "pin": ("Pin", "regular"), "pin-filled": ("Pin", "filled"),
    "minimize": ("Line Horizontal 1", "regular"), "maximize": ("Maximize", "regular"),
    "restore": ("Square Multiple", "regular"),
}

def fetch(folder, style):
    snake = folder.lower().replace(" ", "_")
    url = f"{BASE}/{urllib.parse.quote(folder)}/SVG/ic_fluent_{snake}_20_{style}.svg"
    with urllib.request.urlopen(url) as r:
        svg = r.read().decode()
    return " ".join(re.findall(r'<path[^>]*\sd="([^"]+)"', svg))

out = ["// SPDX-License-Identifier: GPL-3.0-or-later",
       "// Generated by tools/gen_icons.py from Microsoft's Fluent UI System Icons (MIT, see",
       "// THIRD-PARTY-LICENSES.txt). 20x20 outlines: draw them with `Icon`.",
       "export global Icons {"]
for name, (folder, style) in ICONS.items():
    try:
        d = fetch(folder, style)
    except Exception as e:  # noqa
        print("missing", name, folder, style, e, file=sys.stderr)
        continue
    out.append(f'    out property <string> {name}: "{d}";')
out.append("}")
p = pathlib.Path(__file__).resolve().parent.parent / "ui" / "icons.slint"
p.write_text("\n".join(out) + "\n")
print("wrote", p, len(out) - 5, "icons")
