// SPDX-License-Identifier: GPL-3.0-or-later
// Every window of the Slint interface. (The zone editor, the side strip, the notifications and
// the recording widget are native: see `vixeeny-overlay`.)
export { Theme, Icons } from "controls.slint";
export { ScrollWindow } from "scroll.slint";
export { WizardWindow } from "wizard.slint";
export { LineItem, MenuOption, SettingGroup, SettingRow, SettingsWindow, ShortcutKey, ShortcutRow, UiTexts } from "settings.slint";
